version: 2.1

executors:
  java:
    working_directory: /tmp/workspace
    docker:
      - image: 991828066748.dkr.ecr.us-east-1.amazonaws.com/circleci_docker_images:java17aws_v1
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY

jobs:
  build:
    executor: java
    steps:
      - checkout
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}-{{ checksum "build.gradle" }}
      - run:
          name: Run gradle build
          command: |
            ./gradlew build
      - run:
          name: Publish artifacts to repository
          command: |
            ./gradlew publish -Dorg.gradle.project.branch="$CIRCLE_BRANCH"
      - store_artifacts:
          path: build/reports
          destination: reports
      - store_test_results:
          path: build/test-results
      - save_cache:
          key: build-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-{{ .Branch }}-{{ checksum "build.gradle" }}
          paths:
            - ~/.gradle

workflows:
  build-develop:
    jobs:
      - build:
          context:
            - aws-global
            - nvirginia-test
          filters:
            branches:
              only: develop
  build-prod:
    jobs:
      - build:
          context:
            - aws-global
            - dublin-prod
          filters:
            branches:
              only:
                - master
                - /^feature.*/
                - /^mindas\/.*/
