syntax = "proto3";

package io.bokun.inventory.service.availability.grpc;

option java_multiple_files = true;
option java_package = "io.bokun.inventory.service.availability.grpc";

import "common.proto";
import "inventory_service_common.proto";

service AvailabilityService {
    // Get detailed info about requested single Bokun product.
    // This returns not only available dates/time but also pickup times as well as pricing for requested range.
    rpc GetProductAvailability (GetProductAvailabilityRequest) returns (stream io.bokun.inventory.common.api.grpc.ProductAvailabilityWithRatesResponse) {}
}

message GetProductAvailabilityRequest {
    // For which Bokun product to find availability/prices for? Mandatory.
    io.bokun.inventory.service.common.grpc.BokunProduct product = 1;

    // For which range to find availability/prices for? Mandatory.
    io.bokun.inventory.common.api.grpc.DatePeriod range = 2;

    // The id of the reseller (vendor ID) who is making this availability call.
    int64 sellerId = 3;
}
